# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrippitySplit' do
    use_frameworks!
    pod 'AWSDynamoDB', '~> 2.6.6'
    pod 'AWSMobileClient', '~> 2.6.6'
    # other pods
end
