//
//  Expense.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Expense: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _name: String?
    var _amount: NSNumber?
    var _date: String?
    
    class func dynamoDBTableName() -> String {

        return "trippitysplit-mobilehub-316143095-Expense"
    }
    
    class func hashKeyAttribute() -> String {

        return "_name"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_name" : "name",
               "_amount" : "amount",
               "_date" : "date",
        ]
    }
}
